function [statenames, avstatenames, robotvars] = get_robotinfo(expname)

% sets robot code states according to the experiment name
% robot states changed as robot code evolved

if ismember(expname, {'Mass','Example'})
    statenames = {'viewmenu' 'startgame' 'home' 'wait4mvt' 'movingout' 'attarget' 'movingback' 'finishmvt' 'intertrial'  'rest' 'warning' ...
        'game_message' 'exitgame'};
    avstatenames = {'blank' 'clear_messagewin' 'show_homeonly' 'show_home' 'show_score' 'show_target' ...
        'show_tooslowtarget' 'show_toofasttarget' 'show_goodjob' 'show_noreward' 'show_aimtarget' 'show_clearhome' ...
        'show_jumptarget' 'show_cleartarget' 'show_cleartargetscore' 'show_score_only' 'rest' ...
        'show_movefaster' 'show_stayincircle' 'show_fail' 'show_messagebox' 'show_gameover'};
    robotvars = {'time' 'time_ms' 'statenumber' 'avstatenumber' 'x' 'y' 'vx' 'vy' 'fx' 'fy' 'ftx' 'fty' 'ftz'};
end

if ismember(expname, {'speed2' 'speedL' 'speedS' 'Curves' 'Mass'})
    statenames = {'viewmenu' 'startgame' 'home' 'wait4mvt' 'movingout' 'attarget' 'movingback' 'finishmvt' 'intertrial'  'rest' 'warning' ...
        'game_message' 'exitgame'};
    avstatenames = {'blank' 'clear_messagewin' 'show_homeonly' 'show_home' 'show_score' 'show_target' ...
        'show_tooslowtarget' 'show_toofasttarget' 'show_goodjob' 'show_clearhome' ...
        'show_jumptarget' 'show_cleartarget' 'rest' ...
        'show_movefaster' 'show_stayincircle' 'show_fail' 'show_messagebox' 'show_gameover'};
    robotvars = {'time' 'time_ms' 'statenumber' 'avstatenumber' 'x' 'y' 'vx' 'vy' 'fx' 'fy' 'ftx' 'fty' 'ftz'};
end

if ismember(expname, {'vm'})
    statenames = {'viewmenu' 'startgame' 'home' 'wait4mvt' 'movingout' 'attarget' 'movingback' 'finishmvt' 'intertrial'  'rest' 'warning' ...
        'game_message' 'exitgame'};
    avstatenames = {'blank' 'clear_messagewin' 'show_homeonly' 'show_home' 'show_score' 'show_target' ...
        'show_tooslowtarget' 'show_toofasttarget' 'show_goodjob' 'show_clearhome' ...
        'show_jumptarget' 'show_cleartarget' 'rest' ...
        'show_movefaster' 'show_stayincircle' 'show_fail' 'show_messagebox' 'show_gameover'};
    robotvars = {'x' 'y' 'vx' 'vy' 'fx' 'fy' 'ftx' 'fty' 'ftz' ...
            'cur_x' 'cur_y' 'cur_pos' 'vrx_px' 'vry_px' 'vr_pos_px' 'vrx_m' 'vry_m' 'vr_pos_m'};
end